# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5bf9e5a123d76356c722a2edd1e778d893da2e1b82627bae73fbc432ee3d6dc5e1d1d0b3effff99f7886c4a02cdffffe8b1cda1e8da87364a98002af4f5a73a2

test:
  secret_key_base: b431e4a969bf36b35fd906fef1bb2bc2b4c52b013866b65443b9fd8bedc981b9529ec573948b2cd8c21b7208c2e0feaf44b7873ab41d29210b0420af7e4e21e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
